from django.urls import path
from . import views

urlpatterns = [
    path('home/', views.home, name='home'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('admin_panel/', views.admin_panel, name='admin_panel'),

    path('custom-admin/surveys/', views.admin_survey_list, name='admin_survey_list'),
    path('custom-admin/notifications/', views.admin_notification_list, name='admin_notification_list'),
    path('custom-admin/events/', views.admin_event_list, name='admin_event_list'),
    path('custom-admin/polls/', views.admin_poll_list, name='admin_poll_list'),

    path('logout/', views.logout_view, name='logout'),
    path('delete_profile/', views.delete_profile, name='delete_profile'),
    path('profile/', views.user_profile, name='profile'),
    path('create_survey/', views.create_survey, name='create_survey'),
    path('create_questions/<int:survey_id>/', views.create_questions, name='create_questions'),
    path('create_answers/<int:survey_id>/', views.create_answers, name='create_answers'),
    path('surveys/', views.survey_list, name='survey_list'),
    path('surveys/<int:survey_id>/', views.take_survey, name='take_survey'),
    path('survey/<int:survey_id>/responses/', views.survey_responses, name='survey_responses'),
    path('survey/<int:survey_id>/user/<int:user_id>/answers/', views.user_survey_responses, name='user_survey_answers'),
    path('survey/<int:survey_id>/delete/', views.delete_survey, name='delete_survey'),
    path('notifications/', views.notification_list, name='notification_list'),
    path('notifications/create/', views.create_notification, name='create_notification'),
    path('delete_notification/<int:notification_id>/', views.delete_notification, name='delete_notification'),
    path('forum/', views.forum_list, name='forum_list'),
    path('forum/create/', views.create_forum_post, name='create_forum_post'),
    path('forum/<int:post_id>/', views.forum_post_detail, name='forum_post_detail'),
    path('forum/<int:post_id>/add_update/', views.create_forum_post_addition, name='create_forum_post_addition'),
    path('forum/<int:post_id>/edit/', views.forum_post_update, name='forum_post_edit'),
    path('forum/<int:post_id>/delete/', views.forum_post_delete, name='forum_post_delete'),
    path('forum/update/<int:update_id>/edit/', views.edit_forum_post_addition, name='edit_forum_post_addition'),
    path('forum_post/addition/delete/<int:addition_id>/', views.delete_addition, name='delete_forum_post_addition'),
    path('portfolio/', views.portfolio_view, name='portfolio'),
    path('events/create/', views.create_event, name='create_event'),
    path('events/calendar/', views.calendar_view, name='calendar_view'),
    path('events/events-json/', views.events_json, name='events_json'),
    path('events/by-date/<str:date>/', views.events_by_date_json, name='events_by_date'),
    path('events/<int:event_id>/', views.event_detail, name='event_detail'),
    path('delete_event/<int:event_id>/', views.delete_event, name='delete_event'),
    path('edit_event/<int:event_id>/', views.edit_event, name='edit_event'),
    path('poll/list/', views.poll_list, name='poll_list'),
    path('create_poll_step_1/', views.create_poll_step_1, name='create_poll_step_1'),
    path('create_poll_step_2/<int:poll_id>/', views.create_poll_step_2, name='create_poll_step_2'),
    path('vote_poll/<int:poll_id>/', views.vote_poll, name='vote_poll'),
    path('poll_results/<int:poll_id>/', views.poll_results, name='poll_results'),
    path('delete_poll/<int:poll_id>/', views.delete_poll, name='delete_poll'),

    path('gallery/', views.gallery_view, name='gallery'),
    path('gallery/upload/', views.upload_gallery_item, name='upload_gallery_item'),
    path('gallery/delete/<int:item_id>/', views.delete_gallery_item, name='delete_gallery_item'),
    path('gallery/edit/<int:item_id>/', views.edit_gallery_item, name='edit_gallery_item'),
    path('gallery/delete/<int:item_id>/', views.delete_gallery_item, name='delete_gallery_item'),
    path('gallery/<int:item_id>/', views.gallery_item_detail, name='gallery_item_detail'),

    path('friends/', views.FriendsView.as_view(), name='friends_list'),
    path('delete_friend/<int:friend_id>/', views.delete_friend, name='delete_friend'),
    path('confirm_friend_request/<int:request_id>/', views.handle_friend_request, name='confirm_friend_request'),
    path('delete_friend_request/<int:request_id>/', views.delete_friend, name='delete_friend_request'),


]
